/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/bootstrap.ts to modify the generation of this file.
const config = {};
config.sitecoreApiKey = process.env.SITECORE_API_KEY || "{363B619E-4D2D-4986-82A8-DC291D17AFB0}",
config.sitecoreApiHost = process.env.SITECORE_API_HOST || "https://ciplacm.dev.local",
config.jssAppName = process.env.JSS_APP_NAME || "breathefree",
config.graphQLEndpointPath = process.env.GRAPH_QL_ENDPOINT_PATH || "/sitecore/api/graph/edge",
config.graphQLEndpoint = process.env.GRAPH_QL_ENDPOINT || `${config.sitecoreApiHost}${config.graphQLEndpointPath}`;
module.exports = config;